### PR TITLE
fix string concat when 'file' is specified

### PR DESCRIPTION
**Pull request by dtzWill**

### CODE REVIEW

**Comment by Mic92** [comment]
This should be fixed here: https://github.com/nix-community/NUR/blob/master/default.nix#L19

**Comment by Mic92** [comment]
This repository is automatically updated from NUR.

**Comment by Infinisil** [comment]
What doesn't work with how it's currently?

**Comment by Mic92** [comment]
According to this it should work:

```console
nix-repl> repoSource = a: b: a
nix-repl> attr = { file = "file"; }
nix-repl> repoSource "a" "b" + "/" + (attr.file or "")
"a/file"
nix-repl> attr = { }
nix-repl> repoSource "a" "b" + "/" + (attr.file or "")
"a/"
```

**Comment by Mic92** [comment]
I see what you mean. I have opened https://github.com/nix-community/NUR/pull/79

**Pull request closed without merging**
